Hello Microverse Project
luisrpavanelli/Microverse-Project pull request #1
Opened 2023-02-16 10:09 UTC by luisrpavanelli

Hello, thank you for help! Your support means a lot to me.

2023-02-16 20:19 UTC, vickymarz requested changes
Hi @luisrpavanelli, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️

- [ ]  I would implore you to add always add a descriptive Pull Request summary describing the changes that you implemented in your pull request so that the reviewer will understand the things you did in the PR. A descriptive PR includes a heading and all the things you've done listed under it.

Writing appreciation as a pull request summary is not professional. So highlight the features you implemented instead 👍🏽 

- [ ] The link to your MIT license in your readme is broken. KIndly add the link to the MIT link or you create a `MIT.md` file including your license text and link it to your readme so as to make your repo more professional 👍🏽 

_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 22:41 UTC, merged

2023-02-16 23:29 UTC, divinecharlotte reviewed
# Hello @luisrpavanelli   😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 
## STATUS: APPROVED
## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-20 20:36 UTC, luisrpavanelli reviewed
Modify the line link, I have left a few comments that should be addressed before this gets merged

2023-02-20 20:42 UTC, luisrpavanelli reviewed
Modify the line link, I have left a few comments that should be addressed before this gets merged

2023-02-20 20:42 UTC, luisrpavanelli commented on README.md
> +[Click here to view]: https://htmlpreview.github.io/?https://github.com/luisrpavanelli/Hello-Microverse-Project/blob/main/index.html
Modify the line link, I have left a few comments that should be addressed before this gets merged

2023-02-20 20:43 UTC, joskalenda reviewed
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @luisrpavanelli , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
| <img src="https://media2.giphy.com/media/2NpKgBuUZtXpu/giphy.gif"/> |

### Highlights
✅ ... Green linters

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._